<?php

/**
 * @file
 * Provides event logging facilities decoupled from storage backend.
 */

/**
 * Implements hook_hook_info_alter().
 */
function logger_hook_info_alter(&$hooks) {
  // Check HOOK.form.inc files for hook_form_alter() implementations.
  $hooks['form_alter']['group'] = 'form';
}

/**
 * Logs a system event.
 *
 * Note: Backends like @link http://graphite.readthedocs.org/ Graphite @endlink
 * interpret dots (.) as path delimiters, like forward slashes (/) in a file
 * path. You need to account for this if part of your event name is dynamically
 * generated and may contain dots. For example:
 *
 * @code
 * $ip_address = str_replace('.', '_', $_SERVER['REMOTE_ADDR']);
 * logger_event(sprintf('server.remote_addr.%s', $ip_address);
 * @endcode
 *
 * @param string $name
 *   The name of the event you want to log.
 * @param string $type
 *   (optional) The type of metric to log--one of the following values
 *   corresponding to the
 *   @link https://github.com/etsy/statsd/blob/master/docs/metric_types.md StatsD Metric Types @endlink
 *   :
 *   - count: The corresponding value is a number by which to increment (or
 *     decrement, if negative) a simple counter.
 *   - gauge: The corresponding value is a single datum, which remains constant
 *     until explicitly changed.
 *   - set: The corresponding value is a value to add to a set of unique values.
 *   - time: The corresponding value is a duration in milliseconds.
 * @param int $value
 *   (optional) The numeric value you wish to log. Defaults to 1.
 *
 * @see hook_logger_event()
 */
function logger_event($name, $type = 'count', $value = 1) {
  // Assert valid event type.
  $valid_types = array('count', 'gauge', 'set', 'time');
  if (!in_array($type, $valid_types)) {
    throw new InvalidArgumentException(sprintf('Invalid event type: "%s".', $type));
  }

  // Assert valid event value.
  if (!is_int($value)) {
    throw new InvalidArgumentException(sprintf('Invalid event value: "%s".', $value));
  }

  // Conditionally log events to watchdog for debugging purposes.
  if (variable_get('logger_debug', FALSE)) {
    watchdog('logger', 'Logger Event: @name | @type | @value', array(
      '@name' => $name,
      '@type' => $type,
      '@value' => $value,
    ), WATCHDOG_DEBUG);
  }

  module_invoke_all('logger_event', $name, $type, $value);
}
